service: rest-api-dynamodb
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-1
  memorySize: 128
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: src/create.create
    events:
      - http:
          path: src
          method: post
          cors: true

  update:
    handler: src/update.update
    events:
      - http:
          path: src/{id}
          method: put
          cors: true

  delete:
    handler: src/delete.delete
    events:
      - http:
          path: src/{id}
          method: delete
          cors: true

  get:
    handler: src/get.get
    events:
      - http:
          path: src/{id}
          method: get
          cors: true

  list:
    handler: src/list.list
    events:
      - http:
          path: user
          method: get
          cors: true

resources:
  Resources:
    LohikaDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}